-- Listing 6-6
-- Using DEK with EKM

USE master;
GO

CREATE ASYMMETRIC KEY TDE_Luna_AsymKey
FROM PROVIDER LunaEKMProvider
WITH ALGORITHM = RSA_2048,
PROVIDER_KEY_NAME = N'TDE_Luna_AsymKey',
CREATION_DISPOSITION = CREATE_NEW;
GO


