-- Listing 5-13
-- Creating a Symmetric Key on the HSM

CREATE SYMMETRIC KEY Luna_AES256_Key
FROM PROVIDER LunaEKMProvider
WITH PROVIDER_KEY_NAME='Luna_AES256_Key',
CREATION_DISPOSITION = CREATE_NEW,
ALGORITHM = AES_256;
