-- Listing 5-5
-- Creating an Asymmetric Key on the HSM

CREATE ASYMMETRIC KEY Luna_RSA2048_Key 
FROM PROVIDER LunaEKMProvider
WITH ALGORITHM = RSA_2048,
PROVIDER_KEY_NAME = 'Luna_RSA2048_Key',
CREATION_DISPOSITION = CREATE_NEW;
